use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'HomeMateModule_Example' do
  pod 'HomeMateModule', :path => '../'

  target 'HomeMateModule_Tests' do
    inherit! :search_paths

    
  end
end
